#!/usr/bin/env bash

set -e

SILENT="-silent"

if [[ "$1" == "--verbose" ]]; then
    SILENT=""
    shift
fi

QT_QPA_PLATFORM=offscreen QT_LOGGING_RULES="qml.debug=true" tests/build/qmltestrunner $SILENT "$@"

